services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: billtrackpro_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1434:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: billtrackpro_backend
    volumes:
      - .:/app
      - /app/obj
      - /app/bin
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BillTrackProDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  sqlvolume:
